### SINGUP

POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "name": "lucas",
    "email": "email@email.com",
    "password": "123456"
}

### LOGIN

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "email@email.com",
    "password": "123456"
}

### QUEUE
POST http://localhost:3000/queue HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2FybmFtZSI6Imx1Y2FzIiwicHJvZmlsZSI6InVzZXIiLCJpZCI6IjU4NzQyOTk5LTZmYjktNDQwYS1iNDliLWEyMTExMjEzN2M1MSIsImlhdCI6MTczNjExOTE0MiwiZXhwIjoxNzM2MTIwMDQyfQ.9IIU8LpdYbfjIAuLPr2p4GaSFMqRYJmQBj-0OibdktE

{
    "color": "#1111de",
    "name": "queue1 test-call",
    "greetingMessage": "message1 test-call"
}


### WHATSAPP 

POST http://localhost:3000/whatsapp HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2FybmFtZSI6Imx1Y2FzIiwicHJvZmlsZSI6InVzZXIiLCJpZCI6IjU4NzQyOTk5LTZmYjktNDQwYS1iNDliLWEyMTExMjEzN2M1MSIsImlhdCI6MTczNjExOTE0MiwiZXhwIjoxNzM2MTIwMDQyfQ.9IIU8LpdYbfjIAuLPr2p4GaSFMqRYJmQBj-0OibdktE

{
    "farewellMessage": "message test-call",
    "greetingMessage": "message test-call",
    "isDefault": false,
    "name": "teste-call2",
    "queueIds": [102]
}

### WHATSAPP 
GET http://localhost:3000/whatsapp/114 HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2FybmFtZSI6Imx1Y2FzIiwicHJvZmlsZSI6InVzZXIiLCJpZCI6IjU4NzQyOTk5LTZmYjktNDQwYS1iNDliLWEyMTExMjEzN2M1MSIsImlhdCI6MTczNjExOTE0MiwiZXhwIjoxNzM2MTIwMDQyfQ.9IIU8LpdYbfjIAuLPr2p4GaSFMqRYJmQBj-0OibdktE

### WHATSAPP 
GET http://localhost:3000/whatsapp HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2FybmFtZSI6Imx1Y2FzIiwicHJvZmlsZSI6InVzZXIiLCJpZCI6IjU4NzQyOTk5LTZmYjktNDQwYS1iNDliLWEyMTExMjEzN2M1MSIsImlhdCI6MTczNjExOTE0MiwiZXhwIjoxNzM2MTIwMDQyfQ.9IIU8LpdYbfjIAuLPr2p4GaSFMqRYJmQBj-0OibdktE

### WHATSAPP 
DELETE  http://localhost:3000/whatsapp/114 HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2FybmFtZSI6Imx1Y2FzIiwicHJvZmlsZSI6InVzZXIiLCJpZCI6ImU4YTcyMDAzLTUyYzktNGI0Ni1iYzViLWQzYTk1NmEzNGRmMyIsImlhdCI6MTczNjExNzU3MCwiZXhwIjoxNzM2MTE4NDcwfQ.69NlLrdUr3hvmlhaCMGlwkweWKi59hGkmDoX17O9kU0