### Variáveis

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2FybmFtZSI6Imx1Y2FzIiwicHJvZmlsZSI6InVzZXIiLCJpZCI6Ijg2ZGVhOTJlLWFjOWQtNDFiMi05MzE1LWJmZWU3NmU1NDc3NiIsImlhdCI6MTczNjIxMDEyOCwiZXhwIjoxNzM2MjExMDI4fQ.qqaJ6ClLTYFEPOKqPyz8leI3kY3n4smpJrwzfstQSmw
@baseUrl = http://localhost:3000

### Autenticação

### SINGUP
POST {{baseUrl}}/signup HTTP/1.1
content-type: application/json

{
    "name": "lucas",
    "email": "email@email.com",
    "password": "123456"
}

### LOGIN
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "email": "email@email.com",
    "password": "123456"
}

### Usuários

### Listar usuários
GET {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Obter usuário
GET {{baseUrl}}/users/9398095a-10aa-4566-92a1-b2f0f7f817af HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Criar usuário
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "user test2",
    "email": "test2@test.com",
    "password": "123456",
    "queueIds": [119,120]
}

### Filas

### Criar fila
POST {{baseUrl}}/queue HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "color": "#1111de",
    "name": "queue1 test-call",
    "greetingMessage": "message1 test-call"
}

### WhatsApp

### Criar WhatsApp
POST {{baseUrl}}/whatsapp HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "farewellMessage": "message test-call",
    "greetingMessage": "message test-call",
    "isDefault": false,
    "name": "teste-call3",
    "queueIds": [120]
}

### Obter WhatsApp
GET {{baseUrl}}/whatsapp/140 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Listar WhatsApp
GET {{baseUrl}}/whatsapp HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Deletar WhatsApp
DELETE {{baseUrl}}/whatsapp/140 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}